use crate::value::ValueType;

#[derive(Clone, Copy, Debug, PartialEq, Eq)]
pub enum BlockType {
    Empty,
    SingleResult(ValueType),
    TypeIndex(u32),
}

#[derive(Clone, Copy, Debug, PartialEq, Eq)]
pub enum Instruction {
    Nop,
    Unreachable,
    Drop,
    I32Const { value: i32 },
    I64Const { value: i64 },
    I32Add,
    I32Sub,
    I32Mul,
    I32DivS,
    I32RemS,
    I32Eqz,
    I32Eq,
    I32Ne,
    I32LtS,
    I32GtS,
    I32LeS,
    I32GeS,
    I64Add,
    I64Sub,
    I64Mul,
    I64DivS,
    I64RemS,
    I64Eqz,
    I64Eq,
    I64Ne,
    I64LtS,
    I64GtS,
    I64LeS,
    I64GeS,
    LocalGet { local_index: u32 },
    LocalSet { local_index: u32 },
    LocalTee { local_index: u32 },
    GlobalGet { global_index: u32 },
    GlobalSet { global_index: u32 },
    I32Load { immediate_offset: u32 },
    I32Store { immediate_offset: u32 },
    I64Load { immediate_offset: u32 },
    I64Store { immediate_offset: u32 },
    MemorySize,
    Block { block_type: BlockType },
    Loop { block_type: BlockType },
    If { block_type: BlockType },
    Else,
    End,
    Br { label_depth: u32 },
    BrIf { label_depth: u32 },
    Call { function_index: u32 },
    Return,
    HostInvoke { host_import_index: u32 },
}

impl Instruction {
    pub fn opcode(self) -> u8 {
        match self {
            Instruction::Nop => 0x00,
            Instruction::Unreachable => 0x01,
            Instruction::Drop => 0x02,
            Instruction::I32Const { .. } => 0x10,
            Instruction::I64Const { .. } => 0x11,
            Instruction::I32Add => 0x20,
            Instruction::I32Sub => 0x21,
            Instruction::I32Mul => 0x22,
            Instruction::I32DivS => 0x23,
            Instruction::I32RemS => 0x24,
            Instruction::I32Eqz => 0x25,
            Instruction::I32Eq => 0x26,
            Instruction::I32Ne => 0x27,
            Instruction::I32LtS => 0x28,
            Instruction::I32GtS => 0x29,
            Instruction::I32LeS => 0x2A,
            Instruction::I32GeS => 0x2B,
            Instruction::I64Add => 0x30,
            Instruction::I64Sub => 0x31,
            Instruction::I64Mul => 0x32,
            Instruction::I64DivS => 0x33,
            Instruction::I64RemS => 0x34,
            Instruction::I64Eqz => 0x35,
            Instruction::I64Eq => 0x36,
            Instruction::I64Ne => 0x37,
            Instruction::I64LtS => 0x38,
            Instruction::I64GtS => 0x39,
            Instruction::I64LeS => 0x3A,
            Instruction::I64GeS => 0x3B,
            Instruction::LocalGet { .. } => 0x40,
            Instruction::LocalSet { .. } => 0x41,
            Instruction::LocalTee { .. } => 0x42,
            Instruction::GlobalGet { .. } => 0x43,
            Instruction::GlobalSet { .. } => 0x44,
            Instruction::I32Load { .. } => 0x50,
            Instruction::I32Store { .. } => 0x51,
            Instruction::I64Load { .. } => 0x52,
            Instruction::I64Store { .. } => 0x53,
            Instruction::MemorySize => 0x54,
            Instruction::Block { .. } => 0x60,
            Instruction::Loop { .. } => 0x61,
            Instruction::If { .. } => 0x62,
            Instruction::Else => 0x63,
            Instruction::End => 0x64,
            Instruction::Br { .. } => 0x65,
            Instruction::BrIf { .. } => 0x66,
            Instruction::Call { .. } => 0x67,
            Instruction::Return => 0x68,
            Instruction::HostInvoke { .. } => 0x70,
        }
    }

    pub fn name(self) -> &'static str {
        match self {
            Instruction::Nop => "nop",
            Instruction::Unreachable => "unreachable",
            Instruction::Drop => "drop",
            Instruction::I32Const { .. } => "i32.const",
            Instruction::I64Const { .. } => "i64.const",
            Instruction::I32Add => "i32.add",
            Instruction::I32Sub => "i32.sub",
            Instruction::I32Mul => "i32.mul",
            Instruction::I32DivS => "i32.div_s",
            Instruction::I32RemS => "i32.rem_s",
            Instruction::I32Eqz => "i32.eqz",
            Instruction::I32Eq => "i32.eq",
            Instruction::I32Ne => "i32.ne",
            Instruction::I32LtS => "i32.lt_s",
            Instruction::I32GtS => "i32.gt_s",
            Instruction::I32LeS => "i32.le_s",
            Instruction::I32GeS => "i32.ge_s",
            Instruction::I64Add => "i64.add",
            Instruction::I64Sub => "i64.sub",
            Instruction::I64Mul => "i64.mul",
            Instruction::I64DivS => "i64.div_s",
            Instruction::I64RemS => "i64.rem_s",
            Instruction::I64Eqz => "i64.eqz",
            Instruction::I64Eq => "i64.eq",
            Instruction::I64Ne => "i64.ne",
            Instruction::I64LtS => "i64.lt_s",
            Instruction::I64GtS => "i64.gt_s",
            Instruction::I64LeS => "i64.le_s",
            Instruction::I64GeS => "i64.ge_s",
            Instruction::LocalGet { .. } => "local.get",
            Instruction::LocalSet { .. } => "local.set",
            Instruction::LocalTee { .. } => "local.tee",
            Instruction::GlobalGet { .. } => "global.get",
            Instruction::GlobalSet { .. } => "global.set",
            Instruction::I32Load { .. } => "i32.load",
            Instruction::I32Store { .. } => "i32.store",
            Instruction::I64Load { .. } => "i64.load",
            Instruction::I64Store { .. } => "i64.store",
            Instruction::MemorySize => "memory.size",
            Instruction::Block { .. } => "block",
            Instruction::Loop { .. } => "loop",
            Instruction::If { .. } => "if",
            Instruction::Else => "else",
            Instruction::End => "end",
            Instruction::Br { .. } => "br",
            Instruction::BrIf { .. } => "br_if",
            Instruction::Call { .. } => "call",
            Instruction::Return => "return",
            Instruction::HostInvoke { .. } => "host.invoke",
        }
    }
}
